/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dashboard": [],
    "scans.index": [],
    "scans.create": [],
    "scans.store": [],
    "scans.show": [
        {
            "name": "scan",
            "required": true
        }
    ],
    "scans.destroy": [
        {
            "name": "scan",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
