/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dashboard": [],
    "scans.index": [],
    "scans.store": [],
    "scans.in-progress": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
